// eslint-disable-next-line import/no-anonymous-default-export
export default {
  login: 'OkanAcioglu',
  id: 110339040,
  node_id: 'U_kgDOBpOj4A',
  avatar_url: 'https://avatars.githubusercontent.com/u/110339040?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/OkanAcioglu',
  html_url: 'https://github.com/OkanAcioglu',
  followers_url: 'https://api.github.com/users/OkanAcioglu/followers',
  following_url:
    'https://api.github.com/users/OkanAcioglu/following{/other_user}',
  gists_url: 'https://api.github.com/users/OkanAcioglu/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/OkanAcioglu/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/OkanAcioglu/subscriptions',
  organizations_url: 'https://api.github.com/users/OkanAcioglu/orgs',
  repos_url: 'https://api.github.com/users/OkanAcioglu/repos',
  events_url: 'https://api.github.com/users/OkanAcioglu/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/OkanAcioglu/received_events',
  type: 'User',
  site_admin: false,
  name: 'Okan Acıoğlu',
  company: null,
  blog: '',
  location: null,
  email: 'okanacioglu@gmail.com',
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 22,
  public_gists: 0,
  followers: 7,
  following: 11,
  created_at: '2022-07-31T13:07:09Z',
  updated_at: '2022-12-19T18:45:20Z',
}
