export default [
  {
    login: 'bimelike',
    id: 47807252,
    node_id: 'MDQ6VXNlcjQ3ODA3MjUy',
    avatar_url: 'https://avatars.githubusercontent.com/u/47807252?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/bimelike',
    html_url: 'https://github.com/bimelike',
    followers_url: 'https://api.github.com/users/bimelike/followers',
    following_url:
      'https://api.github.com/users/bimelike/following{/other_user}',
    gists_url: 'https://api.github.com/users/bimelike/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/bimelike/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/bimelike/subscriptions',
    organizations_url: 'https://api.github.com/users/bimelike/orgs',
    repos_url: 'https://api.github.com/users/bimelike/repos',
    events_url: 'https://api.github.com/users/bimelike/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/bimelike/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'ziyacaylan',
    id: 83708039,
    node_id: 'MDQ6VXNlcjgzNzA4MDM5',
    avatar_url: 'https://avatars.githubusercontent.com/u/83708039?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ziyacaylan',
    html_url: 'https://github.com/ziyacaylan',
    followers_url: 'https://api.github.com/users/ziyacaylan/followers',
    following_url:
      'https://api.github.com/users/ziyacaylan/following{/other_user}',
    gists_url: 'https://api.github.com/users/ziyacaylan/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/ziyacaylan/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ziyacaylan/subscriptions',
    organizations_url: 'https://api.github.com/users/ziyacaylan/orgs',
    repos_url: 'https://api.github.com/users/ziyacaylan/repos',
    events_url: 'https://api.github.com/users/ziyacaylan/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ziyacaylan/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'melisaeldem',
    id: 96880942,
    node_id: 'U_kgDOBcZJLg',
    avatar_url: 'https://avatars.githubusercontent.com/u/96880942?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/melisaeldem',
    html_url: 'https://github.com/melisaeldem',
    followers_url: 'https://api.github.com/users/melisaeldem/followers',
    following_url:
      'https://api.github.com/users/melisaeldem/following{/other_user}',
    gists_url: 'https://api.github.com/users/melisaeldem/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/melisaeldem/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/melisaeldem/subscriptions',
    organizations_url: 'https://api.github.com/users/melisaeldem/orgs',
    repos_url: 'https://api.github.com/users/melisaeldem/repos',
    events_url: 'https://api.github.com/users/melisaeldem/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/melisaeldem/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'scdaslan',
    id: 108617971,
    node_id: 'U_kgDOBnlg8w',
    avatar_url: 'https://avatars.githubusercontent.com/u/108617971?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/scdaslan',
    html_url: 'https://github.com/scdaslan',
    followers_url: 'https://api.github.com/users/scdaslan/followers',
    following_url:
      'https://api.github.com/users/scdaslan/following{/other_user}',
    gists_url: 'https://api.github.com/users/scdaslan/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/scdaslan/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/scdaslan/subscriptions',
    organizations_url: 'https://api.github.com/users/scdaslan/orgs',
    repos_url: 'https://api.github.com/users/scdaslan/repos',
    events_url: 'https://api.github.com/users/scdaslan/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/scdaslan/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'sezerkulekci',
    id: 108686809,
    node_id: 'U_kgDOBnpt2Q',
    avatar_url: 'https://avatars.githubusercontent.com/u/108686809?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/sezerkulekci',
    html_url: 'https://github.com/sezerkulekci',
    followers_url: 'https://api.github.com/users/sezerkulekci/followers',
    following_url:
      'https://api.github.com/users/sezerkulekci/following{/other_user}',
    gists_url: 'https://api.github.com/users/sezerkulekci/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/sezerkulekci/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/sezerkulekci/subscriptions',
    organizations_url: 'https://api.github.com/users/sezerkulekci/orgs',
    repos_url: 'https://api.github.com/users/sezerkulekci/repos',
    events_url: 'https://api.github.com/users/sezerkulekci/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/sezerkulekci/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Alioglumusa',
    id: 109859611,
    node_id: 'U_kgDOBoxTGw',
    avatar_url: 'https://avatars.githubusercontent.com/u/109859611?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Alioglumusa',
    html_url: 'https://github.com/Alioglumusa',
    followers_url: 'https://api.github.com/users/Alioglumusa/followers',
    following_url:
      'https://api.github.com/users/Alioglumusa/following{/other_user}',
    gists_url: 'https://api.github.com/users/Alioglumusa/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Alioglumusa/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Alioglumusa/subscriptions',
    organizations_url: 'https://api.github.com/users/Alioglumusa/orgs',
    repos_url: 'https://api.github.com/users/Alioglumusa/repos',
    events_url: 'https://api.github.com/users/Alioglumusa/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Alioglumusa/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Yusufefedede',
    id: 109877958,
    node_id: 'U_kgDOBoyaxg',
    avatar_url: 'https://avatars.githubusercontent.com/u/109877958?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Yusufefedede',
    html_url: 'https://github.com/Yusufefedede',
    followers_url: 'https://api.github.com/users/Yusufefedede/followers',
    following_url:
      'https://api.github.com/users/Yusufefedede/following{/other_user}',
    gists_url: 'https://api.github.com/users/Yusufefedede/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Yusufefedede/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/Yusufefedede/subscriptions',
    organizations_url: 'https://api.github.com/users/Yusufefedede/orgs',
    repos_url: 'https://api.github.com/users/Yusufefedede/repos',
    events_url: 'https://api.github.com/users/Yusufefedede/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Yusufefedede/received_events',
    type: 'User',
    site_admin: false,
  },
]
